### ISSUE TITLE
vector.js randomDirection explanation

### ISSUE THREAD

**Issue by Gladskih** [evanw/lightgl.js#31]
Why do you use `Math.asin(Math.random() * 2 - 1))` instead of straightforward `Math.random() * Math.PI - Math.PI / 2` in Vector.randomDirection?

**Comment by evanw** [comment]
Vector.randomDirection is intended to be a uniform sample from the surface of a unit sphere. Picking a random angle ends up biasing the result toward the poles of the sphere, so the samples aren't uniform. I think this article explains why pretty well: http://corysimon.github.io/articles/uniformdistn-on-sphere/.
