### ISSUE TITLE
uint8array-json-parser

### ISSUE THREAD

**Issue by babarlelephant** [evanw/lightgl.js#32]
https://www.npmjs.com/package/uint8array-json-parser

Hi, sorry to bother you about this old code, it works fine (and it is the only solution I found to load a large json file on 32bit browsers when it isn't allowed to cut the json in smaller pieces) but it may be a bit too slow (mine is >300MB, once compressed it is 25MB).

Do you think we should go directly ask V8 for a native implementation? (it should be just a cast of the pointer used in JSON.parse)
Or maybe they prefer to parse a string because it is immutable? If so is there any solution?

**Comment by evanw** [comment]
_Note to anyone else reading this: this is the wrong repo. The repo is here instead: https://github.com/evanw/uint8array-json-parser._

> Do you think we should go directly ask V8 for a native implementation?

You are welcome to. I'm not connected at all with the V8 team though, so I'm not going to be able to help you. I assume the best avenues for doing this are asking for an API from node instead if you only need it in node, or trying to advocate for getting it into the JavaScript language standard if you need it in the browser. The node route seems much easier. Adding an API to JavaScript is hard but not impossible. You'd need to advocate for it yourself though. Instructions for how to do that are [here](https://github.com/tc39/ecma262/blob/c328b0aded262172094e1d9a44be216fc67b0632/CONTRIBUTING.md#creating-a-new-proposal).
